### ISSUE TITLE
Rendering issue in Chrome

### ISSUE THREAD

**Issue by sirwart** [frictionlessdata/website-old#15]
The frictionlessdata tab in the top-right doesn't render correctly in Safari. I was able to fix it by disabling the transform property. I believe it's caused by the perspective transform overriding the zindex

<img width="1387" alt="screenshot 2016-05-02 17 18 21" src="https://cloud.githubusercontent.com/assets/830101/14958248/1ca6a95c-108a-11e6-8d7d-2aecf9320cb8.png">
<img width="1387" alt="screenshot 2016-05-02 17 18 28" src="https://cloud.githubusercontent.com/assets/830101/14958249/1ccd1718-108a-11e6-9545-3bdded75864a.png">

**Comment by rufuspollock** [comment]
@sirwart is this Chrome or Safari - i thought Safari ...

**Comment by sirwart** [comment]
Definitely Safari; I have no idea why I typed Chrome. Sorry!

**Comment by rufuspollock** [comment]
@sirwart thanks and good catch.

@smth can you look at this. Also I note bugginess in the OK "badge" on e.g. http://goodtables.okfnlabs.org/ (part of "black" icon showing"):

![image](https://cloud.githubusercontent.com/assets/180658/15027102/d78e8540-1239-11e6-9222-fa02207be87c.png)

**Comment by smth** [comment]
Thanks @sirwart This element is being updated shortly I believe. I shall make sure this is fixed in the next version.

@rgrp that second issue looks like it is caused by using new CSS but old logo. It could be fixed by replacing `//okfnlabs.org/ok-panel/assets/css/frontend.css` with `//cdn.rawgit.com/okfn/ok-panel/v1.0.0/assets/css/frontend.css`. The new logo is being rolled out as we speak though, so will probably be fixed before too long.

**Comment by rufuspollock** [comment]
@smth hmmm - generally it would be nice _not_ to require existing sites to make css changes on upgrade (we have a lot of them and going through all of them and changing css location is a pain). If we are changing the "image" but keeping its url could we not do the same with the css so it was a seamless upgrade for clients? (Or am i misunderstanding the issue)

**Comment by smth** [comment]
It's the other way around in this case (and shouldn't have happened). But yes, going forward, it should be seamless.

Old method (action required to update) http://okfnlabs.org/ok-panel/
New method (seamless) https://a.okfn.org/html/oki/panel/

**Comment by rufuspollock** [comment]
@smth is there a way to fix this so we don't have to go through all the sites and fix - i.e. could we still make a change to the current deploy of the panel?

**Comment by smth** [comment]
Which fix are you referring to?
In either case, the decision has been made to move the files, so every site is being updated anyway.

**Comment by rufuspollock** [comment]
@smth surely we are implementing redirects in our DNS system ;-) - so sites do _not_ have to go an update?

**Comment by smth** [comment]
You'll need to ask someone who is working on this, Paul or Lindsay. I would assume though that a redirect would have the same effect, serving to the latest version, and so fixing any issue you are seeing.

**Comment by pwalsh** [comment]
@rgrp there are a finite number of sites running the panel; updating to use the new assets is manageable, more explicit for those who come after us, and has less potential for unintended breakage, so I do not intend to start maintaining granular redirects for the various assets in the panel and elsewhere (it is not just a matter of a DNS redirect).

**Comment by smth** [comment]
I have just pushed a change that will fix the logo issue, in the interim.

**Comment by rufuspollock** [comment]
@smth this still does not look fixed to me in Safari - can you double check. It would be good to close this.

**Comment by smth** [comment]
It hadn't been updated. This PR will fix it https://github.com/frictionlessdata/frictionlessdata.io/pull/25 (the previous fix was for your Goodtables issue).
